const fs = require('fs');

const translations = {
  "menu.file": "Archivo",
  "menu.file.new": "Nuevo Proyecto...",
  "menu.file.save": "Guardar",
  "menu.file.saveAs": "Guardar Como...",
  "menu.file.saveTemplate": "Guardar Como Plantilla...",
  "menu.file.load": "Cargar Proyecto...",
  "menu.file.importImage": "Importar Imagen...",
  "menu.file.export": "Exportar Como...",
  "menu.file.generate": "Generar Código...",
  "menu.edit": "Editar",
  "menu.edit.undo": "Deshacer",
  "menu.edit.redo": "Rehacer",
  "menu.edit.duplicate": "Duplicar",
  "menu.edit.delete": "Eliminar",
  "menu.object": "Objeto",
  "menu.object.toPath": "Convertir a Trazado",
  "menu.view": "Ver",
  "menu.view.fit": "Ajustar Lienzo a la Vista",
  "menu.view.fullscreen": "Pantalla Completa",
  "menu.view.exitFullscreen": "Salir de Pantalla Completa",
  "menu.view.grid": "Cuadrícula",
  "menu.view.snap": "Ajustar a la Cuadrícula",
  "menu.view.rulers": "Reglas",
  "menu.view.theme": "Tema",
  "menu.view.theme.dark": "Oscuro",
  "menu.view.theme.light": "Claro",
  "menu.help": "Ayuda",
  "menu.help.about": "Acerca de",
  "menu.help.manual": "Manual",
  "menu.help.feedback": "Enviar Comentarios",
  "export.title": "Exportar Imagen",
  "export.format": "Formato:",
  "export.formatDesc": "Elige el formato del archivo de exportación.",
  "export.scale": "Escala:",
  "export.scaleDesc": "Multiplicador de tamaño. 2x hará la imagen el doble de grande.",
  "export.quality": "Calidad:",
  "export.qualityDesc": "Calidad de compresión JPEG de 0 (baja) a 100 (alta).",
  "export.action": "Exportar",
  "apikey.title": "Gestión de la Clave API de Gemini",
  "apikey.hide": "Ocultar clave",
  "apikey.show": "Mostrar clave",
  "apikey.close": "Cerrar",
  "apikey.warning1": "<strong>Importante:</strong> Tu clave API solo se almacenará durante esta sesión y se eliminará al recargar la página. No se guarda de forma permanente por tu seguridad.",
  "apikey.placeholder": "Pega tu clave API aquí",
  "apikey.whereToGet": "¿Dónde conseguir una clave API?",
  "apikey.backToInput": "← Volver a introducir la clave",
  "apikey.howToGetTitle": "Cómo conseguir una clave API de Gemini",
  "apikey.howToGet1": "Puedes obtener una clave API gratuita para usar los modelos Gemini en Google AI Studio.",
  "apikey.step1": "<li>Ve a <a href=\"https://aistudio.google.com/app/apikey\" target=\"_blank\" rel=\"noopener noreferrer\" className=\"underline text-[var(--accent-primary)] hover:text-[var(--accent-primary-hover)]\">Google AI Studio</a>.</li>",
  "apikey.step2": "<li>Inicia sesión con tu cuenta de Google.</li>",
  "apikey.step3": "<li>Haz clic en el botón <strong>\"Create API key in new project\"</strong>.</li>",
  "apikey.step4": "<li>Tu clave se generará en unos segundos. Parecerá una cadena larga de caracteres.</li>",
  "apikey.step5": "<li>Haz clic en el icono de copiar junto a la clave.</li>",
  "apikey.step6": "<li>Vuelve aquí y pega la clave copiada en el campo superior.</li>",
  "apikey.warning2": "<strong>Importante:</strong> Guarda tu clave en un lugar seguro. El editor no la guarda de forma permanente y solo la transmite directamente a la API de Google al generar código.",
  "apikey.delete": "Eliminar clave",
  "action.cancel": "Cancelar",
  "action.cancel2": "Cancelar",
  "action.close": "Cerrar",
  "action.save": "Guardar",
  "dash.solid": "Línea Continua",
  "dash.solid.desc": "Línea sólida sin guiones",
  "dash.simple": "Guion Simple",
  "dash.simple.desc": "Guion 5px, espacio 3px",
  "dash.long": "Guiones Largos",
  "dash.long.desc": "Guion 10px, espacio 5px",
  "dash.dots": "Puntos Pequeños",
  "dash.dots.desc": "Guion 2px, espacio 2px",
  "dash.sparseDots": "Puntos Dispersos",
  "dash.sparseDots.desc": "Guion 2px, espacio 4px",
  "dash.dashDot": "Guion-Punto",
  "dash.dashDot.desc": "Guion 10px, espacio 3px, punto 2px",
  "dash.dashTwoDots": "Guion-Dos-Puntos",
  "dash.dashTwoDots.desc": "Guion y 2 puntos",
  "dash.doubleDot": "Doble Punto",
  "dash.doubleDot.desc": "Doble punto",
  "dash.longShort": "Guion Largo+Corto",
  "dash.longShort.desc": "Guiones largos y cortos",
  "code.comment.shapes": "# --- Shapes (Objects) ---",
  "code.comment.noShapes": "# No hay figuras para dibujar",
  "app.1100": "Herramientas",
  "app.1101": "Fuentes Tkinter",
  "app.1102": "Figura duplicada.",
  "app.1103": "Figura convertida a trazado.",
  "app.1104": "Polígono",
  "app.1105": "Polilínea",
  "app.1106": "Curva de Bezier",
  "app.1107": "El modo de edición de puntos no está disponible para texto.",
  "app.1108": "¡Dibuja algo en el lienzo primero!",
  "app.1109": "Por favor, introduce tu clave API de Gemini en la configuración.",
  "app.1110": "¡Código generado con éxito!",
  "app.1111": "Ocurrió un error desconocido.",
  "app.1112": "Error al generar el código:",
  "app.1113": "Error de generación de código.",
  "app.1114": "Lienzo borrado.",
  "app.1115": "¿Borrar lienzo?",
  "app.1116": "¿Crear nuevo proyecto?",
  "app.1117": "Todos los cambios no guardados se perderán. ¿Estás seguro?",
  "app.1118": "¿Volver al inicio?",
  "app.1119": "Tienes cambios sin guardar. Tu trabajo se guarda automáticamente. Si sales, podrás restaurar la última versión guardada automáticamente en tu próximo inicio. ¿Deseas salir a la pantalla principal?",
  "app.1120": "Sí, salir",
  "app.1121": "Cancelar",
  "app.1122": "No hay cambios sin guardar.",
  "app.1123": "Error al guardar en el archivo",
  "app.1124": "Error al guardar. Intenta con \"Guardar como...\".",
  "app.1000": "Proyecto Vectorial",
  "app.1001": "Proyecto guardado.",
  "app.1002": "Error al guardar el proyecto",
  "app.1003": "Error al guardar el proyecto.",
  "app.1004": "Proyecto (desde plantilla",
  "app.1005": "Plantilla \"",
  "app.1006": "\" guardada.",
  "app.1007": "Error al guardar la plantilla.",
  "app.1008": "¿Eliminar plantilla?",
  "app.1009": "Esta acción eliminará permanentemente la plantilla. ¿Estás seguro?",
  "app.1010": "Plantilla eliminada.",
  "app.1011": "Error al eliminar la plantilla.",
  "app.1012": "Plantilla renombrada.",
  "app.1013": "Error al renombrar la plantilla.",
  "app.1014": "Proyecto cargado",
  "app.1015": "Proyecto cargado con éxito.",
  "app.1016": "Formato de archivo de proyecto no válido.",
  "app.1017": "Error al analizar el archivo",
  "app.1018": "Error al cargar. El archivo está dañado.",
  "app.1019": "Error al cargar el proyecto a través de la API",
  "app.1020": "¿Cargar proyecto?",
  "app.1021": "Se perderán los cambios sin guardar. ¿Estás seguro?",
  "app.1022": "Error al cargar el proyecto. El archivo podría estar dañado.",
  "app.1023": "Error al leer el archivo.",
  "app.1024": "Exportando imagen...",
  "app.1025": "Imagen SVG",
  "app.1026": "Imagen PNG",
  "app.1027": "Imagen JPEG",
  "app.1028": "¡Imagen exportada con éxito!",
  "app.1029": "Error de exportación:",
  "app.1030": "Error al exportar la imagen.",
  "app.1031": "Error al abrir el proyecto reciente:",
  "app.1032": "Error al abrir el proyecto:",
  "app.1033": "Error desconocido",
  "app.1034": "Eliminar \"",
  "app.1036": "Esta acción solo eliminará el proyecto de la lista reciente, no el archivo en sí. ¿Estás seguro?",
  "app.1037": "Proyecto eliminado de la lista.",
  "app.1038": "¿Borrar la lista de proyectos recientes?",
  "app.1039": "Esta acción eliminará todos los proyectos de la lista, pero no los archivos en sí. ¿Estás seguro?",
  "app.1040": "Lista de proyectos recientes borrada.",
  "app.1041": "No hay código para guardar.",
  "app.1042": "Archivo Python",
  "app.1043": "Archivo de texto",
  "app.1044": "Archivo guardado con éxito.",
  "app.1045": "Error al guardar el archivo:",
  "app.1046": "Error al guardar el archivo.",
  "app.1047": "No hay código para ejecutar.",
  "app.1048": "Código copiado al portapapeles.",
  "app.1049": "Error al crear el enlace para el IDE en línea.",
  "app.1050": "Código demasiado grande",
  "app.1051": "El código es demasiado grande para abrirlo en el IDE en línea debido a los límites de URL. Puedes copiarlo y pegarlo manualmente.",
  "app.1052": "Intentar de todos modos",
  "app.1053": "Copiar código e ir",
  "app.1054": "Copia el código al portapapeles y abre EPython list para pegarlo manualmente",
  "app.1055": "Navegando a recurso externo",
  "app.1056": "Estás a punto de abrir el código en el editor en línea EPython. ¿Continuar?",
  "app.1057": "Sí, ir",
  "app.1058": "Quedarse",
  "app.1059": "Error al entrar en modo de pantalla completa:",
  "app.1060": "Cambio a generador local. El código se actualizará automáticamente.",
  "app.1061": "Clave API guardada para la sesión actual.",
  "app.1062": "Clave API eliminada.",
  "app.1063": "Proyecto guardado automáticamente.",
  "app.1064": "Error de guardado automático.",
  "app.1065": "Versión guardada automáticamente eliminada.",
  "app.1066": "Tamaño de pantalla demasiado pequeño",
  "app.1067": "Lamentablemente, el editor requiere una pantalla más grande.",
  "app.1068": "Por favor abre la app en un PC, tablet, o rota la pantalla.",
  "app.1069": "Nuevo dibujo. VereTka",
  "app.1070": "Error al cargar el proyecto.",
  "template.save": "Guardar plantilla...",
  "template.saveAsTemplate": "Guardar como plantilla",
  "template.new": "Nueva plantilla",
  "template.name": "Nombre de plantilla:",
  "template.desc": "Descripción de plantilla:",
  "project.new": "Nuevo proyecto",
  "project.createFrom": "Crear desde:",
  "project.blankCanvas": "Lienzo en blanco",
  "project.yourTemplates": "Tus plantillas",
  "project.shapes": "obj.",
  "project.name": "Nombre del proyecto:",
  "project.canvasSettings": "Configuración del lienzo",
  "project.width": "Ancho:",
  "project.height": "Alto:",
  "project.canvasName": "Nombre del lienzo:",
  "project.idWarning": "(Solo letras latinas, números y \"_\". No puede empezar por número)",
  "project.bgColor": "Color de fondo:",
  "action.create": "Crear",
  "feedback.title": "Dejar comentarios",
  "feedback.p1": "Tus comentarios son importantes. Reportes de errores, ideas y sugerencias ayudan a mejorar.",
  "feedback.p2": "La forma más conveniente es llenar un formulario de Google Form. Solo tomará unos minutos.",
  "feedback.note": "<strong>Nota:</strong> Los datos del SO, navegador y editor se adjuntarán automáticamente.",
  "feedback.goto": "Ir al formulario de comentarios",
  "about.title": "Acerca del editor VereTka",
  "about.p1": "<strong className=\"text-[var(--text-primary)]\">VereTkа</strong> es un editor vectorial para generación de código Tkinter.",
  "about.p2": "Usa un generador local y soporte a la IA Gemini de forma experimental.",
  "about.author": "<strong className=\"text-[var(--text-primary)]\">Idea y Desarrollo:</strong> Vitaliy Kushnir",
  "about.support": "<strong className=\"text-[var(--text-primary)]\">Soporte:</strong> IA Gemini de Google.",
  "about.tech": "Creado con <a href=\"https://aistudio.google.com/\" target=\"_blank\">AI Studio Google</a>, VS Code.",
  "about.version": "Versión",
  "help.intro": "1. Introducción",
  "help.interface": "2. Descripción de la interfaz",
  "help.projects": "3. Trabajar con proyectos",
  "help.templates": "4. Trabajar con plantillas",
  "help.shapes": "5. Trabajar con figuras",
  "help.codeExport": "6. Código y exportación",
  "help.feedback": "7. Comentarios",
  "help.hotkeys": "8. Atajos de teclado",
  "saveAs.title": "Guardar como...",
  "tool.imageImport": "Importar [imagen]",
  "canvas.shapeDuplicated": "Figura duplicada.",
  "canvas.finish": "Terminar",
  "canvas.closePoly": "Cerrar trazado",
  "canvas.duplicating": "Duplicando",
  "canvas.angle": "Ángulo",
  "selection.anchorPoint": "Punto de anclaje",
  "code.saveFileAs": "Guardar código como...",
  "code.saveDesc": "Asigna un nombre y selecciona la extensión.",
  "code.fileNameDesc": "Introduce el nombre del archivo.",
  "code.fileName": "Nombre del archivo:",
  "code.selectExt": "Seleccionar extensión",
  "code.saveLineNumbers": "Con números de línea",
  "code.saveLineNumbersDesc": "Añadir números de línea en el archivo de texto.",
  "cheat.reset": "Todos los trucos restablecidos.",
  "cheat.activated": "Truco desactivado!",
  "cheat.invalid": "Código inválido",
  "cheat.formatError": "Formato inválido. Esperado #000.",
  "cheat.title": "Introduce truco",
  "cheat.desc": "Introduce tu código truco",
  "cheat.activate": "Activar",
  "preview.title": "Vista previa",
  "status.toggleCoords": "Mostrar/Ocultar coordenadas",
  "status.coords": "Coordenadas del ratón",
  "status.zoom": "Zoom",
  "status.zoomClick": "Haz clic para cambiar zoom",
  "status.showSelected": "Mostrar seleccionado",
  "welcome.thumbnail": "Miniatura",
  "help.title": "Asistencia y Manual",
  "help.search": "Buscar...",
  "help.clearSearch": "Borrar",
  "help.prevResult": "Resultado anterior",
  "help.nextResult": "Resultado siguiente",
  "help.notFound": "No encontrado",
  "help.zoomOut": "Alejar (zoom -)",
  "help.zoomIn": "Acercar (zoom +)",
  "help.resetZoom": "Resetear zoom",
  "help.close": "Cerrar",
  "menu.home": "Inicio",
  "menu.settings": "Ajustes",
  "tool.select": "Seleccionar",
  "tool.editPoints": "Editar Puntos",
  "tool.rectangle": "Rectángulo",
  "tool.square": "Cuadrado",
  "tool.circle": "Círculo",
  "tool.ellipse": "Elipse",
  "tool.line": "Línea",
  "tool.polyline": "Polilínea",
  "tool.bezier": "Curva Bezier",
  "tool.arc": "Arco",
  "tool.pieslice": "Sector (Pie)",
  "tool.chord": "Cuerda",
  "tool.polygon": "Polígono",
  "tool.star": "Estrella",
  "tool.triangle": "Triángulo",
  "tool.rightTriangle": "Triángulo Rectángulo",
  "tool.rhombus": "Rombo",
  "tool.trapezoid": "Trapecio",
  "tool.parallelogram": "Paralelogramo",
  "tool.text": "Texto",
  "tool.pencil": "Lápiz",
  "tool.image": "Imagen",
  "tool.bitmap": "Mapa de bits (Bitmap)",
  "prop.fill": "Relleno",
  "prop.stroke": "Trazo",
  "prop.width": "Grosor",
  "prop.sides": "Lados/Puntas",
  "prop.color": "Color",
  "prop.font": "Fuente",
  "prop.size": "Tamaño",
  "prop.drawMode.corner": "Dibujo desde la Esquina",
  "prop.drawMode.center": "Dibujo desde el Centro",
  "prop.dash": "Guión",
  "action.clear": "Limpiar",
  "action.generate": "Generar Código",
  "action.generating": "Generando...",
  "action.placeImage": "Haz clic en el lienzo para colocar la imagen.",
  "style.bold": "Negrita",
  "style.italic": "Cursiva",
  "style.underline": "Subrayado",
  "style.strikethrough": "Tachado",
  "align.left": "Izquierda",
  "align.center": "Centro",
  "align.right": "Derecha",
  "settings.title": "Ajustes",
  "settings.close": "Cerrar",
  "settings.tab.canvas": "Lienzo",
  "settings.tab.grid": "Cuadrícula",
  "settings.tab.appearance": "Apariencia",
  "settings.tab.code": "Código",
  "settings.tab.templates": "Plantillas",
  "settings.appearance.interface": "Interfaz",
  "settings.appearance.language": "Idioma",
  "settings.appearance.showTkinterNames": "Nombres Tkinter",
  "settings.appearance.showTkinterNamesDesc": "Mostrar nombres de comandos p.ej. Rectangle [rectangle]",
  "settings.appearance.showAxes": "Mostrar reglas",
  "settings.appearance.showAxesDesc": "Mostrar reglas superior e izquierda.",
  "settings.appearance.showCursorCoords": "Mostrar coordenadas del cursor",
  "settings.appearance.showCursorCoordsDesc": "Muestra las coordenadas X/Y junto al ratón.",
  "settings.appearance.showRotationAngle": "Mostrar ángulo de rotación",
  "settings.appearance.showRotationAngleDesc": "Mostrar tooltip al rotar un objeto.",
  "settings.appearance.homeScreen": "Pantalla de Inicio",
  "settings.appearance.maxRecentProjects": "Proyectos recientes:",
  "settings.appearance.maxRecentProjectsDesc": "Número máximo de proyectos en Inicio.",
  "settings.canvas.size": "Tamaño del lienzo",
  "settings.canvas.width": "Ancho:",
  "settings.canvas.height": "Alto:",
  "settings.canvas.background": "Fondo",
  "settings.canvas.bgColor": "Color:",
  "settings.canvas.codeDisplay": "Representación del Código",
  "settings.canvas.varName": "Nombre Variable:",
  "settings.canvas.varNameDesc": "(Solo caracteres latinos y guiones bajos)",
  "settings.grid.settings": "Ajustes de Cuadrícula",
  "settings.grid.size": "Tamaño:",
  "settings.grid.snapStep": "Ajuste (Snap):",
  "settings.code.generatorMethod": "Método de Generación",
  "settings.code.local": "Generador Local",
  "settings.code.localDesc": "Rápido y offline. Opción recomendada.",
  "settings.code.gemini": "Generador Gemini",
  "settings.code.geminiDesc": "Requiere API Key.",
  "settings.code.manageKey": "Gestionar API Key",
  "settings.code.settings": "Ajustes de código",
  "settings.code.outline": "Añadir outline=''",
  "settings.code.outlineDesc": "Añade un borde a los elementos rellenos para que no tengan un borde de 1px por defecto.",
  "settings.code.comments": "Comentarios automáticos",
  "settings.code.commentsDesc": "Generar descripciones en el código para cada objeto.",
  "settings.code.lineNumbers": "Números de línea",
  "settings.code.lineNumbersDesc": "Mostrarlos en la ventana de código.",
  "settings.code.highlight": "Resaltar código",
  "settings.code.highlightDesc": "Resaltar la línea en el editor de código al seleccionar un objeto.",
  "settings.templates.title": "Tus plantillas",
  "settings.templates.rename": "Renombrar",
  "settings.templates.delete": "Eliminar",
  "settings.templates.empty": "No hay plantillas.",
  "welcome.autosave.found": "¡Autorrecuperación encontrada!",
  "welcome.autosave.message": "El proyecto \"{name}\" se guardó a las {time}.",
  "welcome.autosave.recently": "recientemente",
  "welcome.autosave.restore": "Restaurar",
  "welcome.autosave.dismiss": "Descartar",
  "welcome.title": "VereTka",
  "welcome.subtitle": "Dibuja para generar código Python (Tkinter)",
  "welcome.description": "Un editor gráfico sencillo",
  "welcome.action.new": "Nuevo Proyecto",
  "welcome.action.newDesc": "Empezar con lienzo en blanco.",
  "welcome.action.load": "Cargar Proyecto",
  "welcome.action.loadDesc": "Abrir *.vec.json",
  "welcome.action.return": "Volver",
  "welcome.action.returnDesc": "Volver a dibujar.",
  "welcome.recent.title": "Recientes",
  "welcome.recent.clear": "Limpiar Historial",
  "welcome.recent.delete": "Quitar de la lista",
  "welcome.recent.noThumbnail": "Sin miniatura",
  "welcome.recent.opened": "Abierto",
  "welcome.recent.empty": "La lista de proyectos recientes está vacía.",
  "welcome.recent.emptyDesc": "Trabaja en un proyecto para que aparezca aquí.",
  "welcome.date.today": "Hoy",
  "welcome.date.yesterday": "Ayer",
  "welcome.date.daysAgo": "hace {days} días",
  "code.title": "Código Tkinter",
  "code.wordWrap.on": "Activar ajuste de línea",
  "code.wordWrap.off": "Desactivar ajuste de línea",
  "code.update": "Actualizar",
  "code.preview": "Vista Previa",
  "code.copy": "Copiar",
  "code.copied": "Copiado!",
  "code.options": "Opciones",
  "code.showComments": "Mostrar Comentarios",
  "code.showLineNumbers": "Mostrar Números de Línea",
  "code.highlight": "Resaltar Selección",
  "code.highlightDesc": "Resalta tu selección del lienzo.",
  "code.saveFile": "Guardar código...",
  "code.saveFileDesc": "Exportar como py/text.",
  "code.openOnline": "Abrir online...",
  "code.openOnlineDesc": "IDE en línea.",
  "code.runOnline": "Ejecutar online...",
  "code.runOnlineDesc": "Ejecutar en EPython.",
  "code.generating": "Generando código Python...",
  "code.error": "Error interno",
  "code.settings": "Ajustes",
  "code.switchToLocal": "Usar Local Generator",
  "code.placeholder.title": "Código",
  "code.placeholder.commentsHidden": "Comentarios ocultos.",
  "code.placeholder.draw": "Empieza a dibujar...",
  "list.title": "Lista de Objetos",
  "list.autoscroll.on": "Auto-scroll: ON",
  "list.autoscroll.noSelection": "Auto-scroll: sin selección",
  "list.autoscroll.visible": "Objeto visible",
  "list.autoscroll.scroll": "Saltar a selección",
  "list.autoscroll.toggle": "Alternar Scroll automático",
  "list.find": "Encontrar",
  "list.visibility.show": "Mostrar",
  "list.visibility.hide": "Ocultar",
  "list.moveUp": "Subir",
  "list.moveDown": "Bajar",
  "list.delete": "Eliminar",
  "list.empty": "Aún no hay objetos.",
  "props.title": "Propiedades",
  "props.empty": "Selecciona un objeto para ver sus propiedades.",
  "props.name": "Nombre:",
  "props.nameDesc": "Variable usada en Tkinter.",
  "props.comment": "Comentario:",
  "props.commentDesc": "Comentario descriptivo para código.",
  "props.commentPlaceholder": "Escribe un comentario",
  "props.commentTooltip": "Sugerencias de comentario",
  "props.geometry": "Geometría",
  "props.x": "X:",
  "props.xDesc": "Coordenada X",
  "props.y": "Y:",
  "props.width": "Ancho:",
  "props.height": "Alto:",
  "props.ratioLocked": "Relación Bloqueada",
  "props.ratioUnlocked": "Relación Desbloqueada",
  "props.lockRatioDesc": "Fijar proporción",
  "props.rotation": "Rotación:",
  "props.rotationDesc": "Ángulo de giro",
  "props.tkinterCoords": "Coordenadas (Tkinter)",
  "props.nodes": "Nodos",
  "props.nodesDesc": "Edición de puntos.",
  "props.nodes.count": "Puntos ({count})",
  "props.nodeDelete": "Borrar punto",
  "props.state": "Estado",
  "props.state.normal": "Normal",
  "props.state.hidden": "Oculto",
  "props.state.disabled": "Desactivado",
  "props.joinstyle": "Estilo de Unión",
  "props.joinstyle.miter": "Inglete (Miter)",
  "props.joinstyle.round": "Redondo",
  "props.joinstyle.bevel": "Bisel (Bevel)",
  "props.capstyle": "Configuración de Puntas",
  "props.capstyle.butt": "Plano (Butt)",
  "props.capstyle.round": "Redondo",
  "props.capstyle.projecting": "Proyectado",
  "props.arrow": "Flechas",
  "props.arrow.none": "Ninguno",
  "props.arrow.first": "Inicio",
  "props.arrow.last": "Fin",
  "props.arrow.both": "Ambos",
  "props.stipple": "Patrón (Stipple)",
  "props.stipple.none": "Ninguno",
  "props.smooth": "Suavizado (Smooth)",
  "props.closed": "Cerrado",
  "props.dashOffset": "Desplazamiento Dash",
  "props.dashOffsetDesc": "Desplazamiento de guiones",
  "props.splinesteps": "Pasos de Curva",
  "prop.title.stipple": "Rellenar figura con patrón",
  "props.stippleNote": "Nota: stipple solo funciona en X11/Linux",
  "prop.title.enableFill": "Activar o desactivar color de relleno.",
  "prop.title.fillColor": "Color del interior del polígono.",
  "prop.title.enableStroke": "Activar o desactivar el trazado (borde)",
  "prop.title.strokeColor": "Color de la línea exterior",
  "prop.title.strokeWidthLine": "Grosor en píxeles del trazado",
  "prop.title.nodeX": "Coordenada X del punto {i}",
  "prop.title.nodeY": "Coordenada Y del punto {i}",
  "prop.title.addNode": "Inyectar nuevo punto (nodo)",
  "prop.title.tkX1": "Coordenada X del rincón superior izquierdo",
  "prop.title.connectEnds": "Unir puntos de inicio y final de forma automática",
  "prop.title.tkY1": "Coordenada Y del rincón superior izquierdo",
  "prop.title.tkX2": "Coordenada X del rincón inferior derecho",
  "prop.title.tkY2": "Coordenada Y del rincón inferior derecho",
  "prop.title.state": "Comportamiento del mouse/eventos globales",
  "prop.title.joinstyle": "Formato de giro al conectar vértices",
  "prop.title.joinstyleDesc": "Ver cómo quedan unidas dos líneas",
  "prop.title.capstyle": "Aspecto final de la punta de la línea",
  "prop.title.capstyleDesc": "Remate final (terminación en plano o curva)",
  "prop.title.addArrows": "Incluye puntas de flecha predefinidas de Tkinter al trazo",
  "prop.title.arrowDesc": "Agrega una o dos flechas",
  "props.arrowTipOffset": "Offset Punta:",
  "prop.title.arrowTipOffset": "Margen de final natural",
  "props.arrowWingsOffset": "Margen Alas:",
  "prop.title.arrowWingsOffset": "Cuán abierta son las aspas",
  "props.arrowWingWidth": "Ancho Aletones:",
  "prop.title.arrowWingWidth": "Ancho de la punta proyectada",
  "prop.title.sides": "Rayos de la figura",
  "props.innerRadius": "Radio Interno:",
  "prop.title.innerRadius": "Escala del pico entrante de la estrella",
  "props.sideLength": "Tamaño de Arista:",
  "prop.title.sideLength": "Dimensión de borde",
  "props.topOffset": "Separación Ascendente:",
  "prop.title.topOffset": "Sesgo en techo",
  "props.symmetric": "Simétrico:",
  "prop.title.symmetric": "Forzar espejado de vértices",
  "props.offsetL": "Margen Izquierdo (%):",
  "prop.title.offsetL": "Porcentaje de inclinación izq.",
  "props.offsetR": "Margen Derecho (%):",
  "prop.title.offsetR": "Porcentaje de inclinación der.",
  "props.angle": "Rotación Interna (º):",
  "prop.title.angle": "Giro de las aristas o biseles",
  "fonts.sans": "Popular Sans-Serif",
  "fonts.serif": "Popular Serif",
  "fonts.mono": "Popular Monospace",
  "fonts.decorative": "Formatos y Displays",
  "fonts.error.notSupported": "Se bloquearon las fuentes locales, navegador obsoleto",
  "fonts.error.notFound": "Sin permiso para registrar tipografías",
  "fonts.success.loaded": "Se han logrado enlazar {count} archivos de fuentes.",
  "fonts.success.noNew": "Sin fuentes",
  "fonts.error.loading": "Imposible cargar el sistema",
  "fonts.error.details": "Revisar consola log.",
  "fonts.error.blocked": "Denegado por política sandbox.",
  "fonts.error.denied": "Permiso rechazado por usted.",
  "props.anchor": "Ancla:",
  "props.anchor.nw": "Sup-Izq (NW)",
  "props.anchor.n": "Norte (N)",
  "props.anchor.ne": "Sup-Der (NE)",
  "props.anchor.w": "Centro Izquierdo (W)",
  "props.anchor.center": "Centro Principal (Center)",
  "props.anchor.e": "Centro Derecho (E)",
  "props.anchor.sw": "Inf-Izq (SW)",
  "props.anchor.s": "Sur (S)",
  "props.anchor.se": "Inf-Der (SE)",
  "props.style": "Familia Tk:",
  "props.startAngle": "Inicio Arc (º):",
  "props.endAngle": "Fin Arc (º):",
  "props.extent": "Amplitud (º):",
  "props.lockExtent": "Fijar Amplitud",
  "props.fonts.system": "Fuentes del Ordenador",
  "props.fonts.tk": "Estándares de UI Tkinter",
  "props.actions": "Eventos de ratón",
  "props.fonts.load": "Sincronizar Tipos Locales",
  "props.fonts.loading": "Buscando...",
  "props.anchorX": "Ancla de texto X:",
  "props.anchorY": "Ancla de texto Y:",
  "props.justify": "Alineación interna:",
  "props.blockWidth": "Contenedor limitante:",
  "props.bitmapType": "Plantilla BitMap:",
  "props.fgColor": "Color positivo (FG):",
  "props.bgColor": "Color negativo (BG):",
  "prop.title.color": "Color de la tinta o rayo principal",
  "prop.title.width": "Grosor exacto de la pincelada base.",
  "prop.title.closed": "Cierra virtualmente un esqueleto",
  "prop.title.smooth": "El propio Tkinter dibujará la curvatura",
  "prop.title.splinesteps": "Resolución de la línea ondulada",
  "prop.title.arcStyle": "Arc: Arco sin relleno. Chord: Cuerda. Pieslice: Porción",
  "prop.title.startAngle": "Ángulo de giro base según reloj invertido",
  "prop.title.endAngle": "Angulo final (solo informativo)",
  "prop.title.extent": "Distancia angular circular total cubierta",
  "prop.title.lockExtent": "Al mover Start, mueve End a la vez",
  "prop.title.text": "Mensaje en pantalla (string literal)",
  "prop.title.font": "Selecciona la fuente base para este rótulo",
  "prop.title.fontSize": "Altura aproximada de la letra (points)",
  "prop.title.textColor": "Color de la tinta de letra",
  "prop.title.textStyle": "Subrayar, Cursiva, etc",
  "prop.title.anchor": "Ancla general visual en la que nace el render",
  "prop.title.anchorX": "Variable X anclaje manual",
  "prop.title.anchorY": "Variable Y",
  "prop.title.justify": "Left, center, right del párrafo.",
  "prop.title.blockWidth": "Max. width para que se divida de línea solo",
  "prop.title.bitmapType": "Bitmap de iconografía vieja de X11 Tk",
  "prop.title.fgColor": "Tintar los píxeles blancos del iconito",
  "prop.title.bgColor": "Tintado de fondo",
  "prop.title.posY": "Eje vertical",
  "prop.title.widthGeom": "Tamaño real calculado tras giros.",
  "prop.title.heightGeom": "Alto real calculado",
  "prop.dash.strokeLen": "Sección sólida (Trazo)",
  "prop.dash.gapLen": "Tramo negro invisible (Gap)",
  "prop.dash.stroke": "Trazo {i} (px):",
  "prop.dash.gap": "Hueco {i} (px):",
  "prop.dash.strokeLenTitle": "Guión",
  "prop.dash.gapLenTitle": "Espacio",
  "prop.dash.removeSegment": "Quitar sección",
  "prop.dash.addSegment": "Añadir sección adicional"
};

let content = fs.readFileSync('lib/translations.ts', 'utf8');

const esMatch = content.match(/es: \{([\s\S]*?)\n  \}/);
let esLines = esMatch[1].split('\n');

for (let i=0; i<esLines.length; i++) {
    let esLine = esLines[i];
    const match = esLine.match(/^(\s*'[^']+':\s*)('.*?'|".*?"),?(.*)$/);
    if (!match) continue;
    
    let key = match[1].trim().replace(/'/g, '').replace(':', '');
    if (translations[key]) {
        let isDoubleQuote = match[2].startsWith('"');
        let translated = translations[key];
        
        let escapedTranslated = translated;
        if (isDoubleQuote) {
            escapedTranslated = escapedTranslated.replace(/"/g, '\\"');
        } else {
            escapedTranslated = escapedTranslated.replace(/'/g, "\\'");
        }
        
        esLines[i] = `${match[1]}${isDoubleQuote ? '"' : "'"}${escapedTranslated}${isDoubleQuote ? '"' : "'"}${match[3] ? ',' + match[3] : ','}`;
    }
}

let esBlock = `es: {\n${esLines.join('\n')}\n  }`;
content = content.replace(/es: \{([\s\S]*?)\n  \}/, esBlock);
fs.writeFileSync('lib/translations.ts', content);
console.log("Translations swapped");
