const fs = require('fs');

const ukEdits = `    'template.save': 'Зберегти шаблон...',
    'template.name': 'Назва шаблону:',
    'template.desc': 'Опис шаблону:',
    'project.new': 'Новий проєкт',
    'project.createFrom': 'Створити з:',
    'project.blankCanvas': 'Чисте полотно',
    'project.yourTemplates': 'Ваші шаблони',
    'project.shapes': 'об.',
    'project.name': 'Назва проєкту:',
    'project.canvasSettings': 'Налаштування полотна',
    'project.width': 'Ширина:',
    'project.height': 'Висота:',
    'project.canvasName': 'Назва полотна:',
    'project.idWarning': '(Лише латинські літери, цифри та "_". Не може починатись з цифри)',
    'project.bgColor': 'Колір тла:',
    'action.create': 'Створити',
    'feedback.title': 'Залишити відгук',
    'feedback.p1': 'Ваш відгук надзвичайно важливий для покращення редактора. Повідомлення про помилки, нові ідеї та просто враження допомагають робити "ВереTkа" кращою.',
    'feedback.p2': 'Найзручніший спосіб поділитися думками — заповнити спеціальну Google Форму. Це займе лише кілька хвилин.',
    'feedback.note': '<strong>Примітка:</strong> Дані про версію редактора, вашу ОС та браузер будуть додані до форми автоматично.',
    'feedback.goto': 'Перейти до форми відгуків',
    'about.title': 'Про редактор "ВереTkа"',
    'about.p1': '<strong className="text-[var(--text-primary)]">ВереTkа</strong> — це простий векторний редактор, призначений для швидкого створення графічних примітивів та генерації відповідного Python коду для бібліотеки Tkinter.',
    'about.p2': 'Він використовує локальний генератор коду для миттєвого та надійного результату, а також може використовувати Google Gemini API для експериментальних можливостей.',
    'about.author': '<strong className="text-[var(--text-primary)]">Ідея та розробка:</strong> Віталій Кушнір',
    'about.support': '<strong className="text-[var(--text-primary)]">Підтримка:</strong> AI-асистент на базі Google Gemini.',
    'about.tech': 'Створено за допомогою <a href="https://aistudio.google.com/" target="_blank" rel="noopener noreferrer" className="underline text-[var(--accent-primary)] hover:text-[var(--accent-primary-hover)]">AI Studio Google</a>, Visual Studio Code.',
    'about.version': 'Версія',
    'help.intro': '1. Вступ',
    'help.interface': '2. Огляд інтерфейсу',
    'help.projects': '3. Робота з проєктами',
    'help.templates': '4. Робота з шаблонами',
    'help.shapes': '5. Робота з об\\'єктами',
    'help.codeExport': '6. Код та експорт',
    'help.feedback': '7. Зворотний зв\\'язок',
    'help.hotkeys': '8. Гарячі клавіші',
    'saveAs.title': 'Зберегти як...',
    'tool.imageImport': 'Зображення [імпорт]',
    'canvas.shapeDuplicated': 'Фігуру дубльовано.',
    'canvas.finish': 'Завершити',
    'canvas.closePoly': 'Замкнути',
    'canvas.duplicating': 'Дублювання',
    'canvas.angle': 'Кут',
    'selection.anchorPoint': 'Точка прив\\'язки тексту',
`;

const enEdits = `    'template.save': 'Save template...',
    'template.name': 'Template name:',
    'template.desc': 'Template description:',
    'project.new': 'New project',
    'project.createFrom': 'Create from:',
    'project.blankCanvas': 'Blank canvas',
    'project.yourTemplates': 'Your templates',
    'project.shapes': 'obj.',
    'project.name': 'Project name:',
    'project.canvasSettings': 'Canvas settings',
    'project.width': 'Width:',
    'project.height': 'Height:',
    'project.canvasName': 'Canvas name:',
    'project.idWarning': '(Only latin letters, numbers and "_". Cannot start with a number)',
    'project.bgColor': 'Background color:',
    'action.create': 'Create',
    'feedback.title': 'Leave feedback',
    'feedback.p1': 'Your feedback is extremely important for improving the editor. Bug reports, new ideas and just impressions help make "VereTkа" better.',
    'feedback.p2': 'The most convenient way to share your thoughts is to fill out a special Google Form. It will only take a few minutes.',
    'feedback.note': '<strong>Note:</strong> Data about the editor version, your OS and browser will be added to the form automatically.',
    'feedback.goto': 'Go to feedback form',
    'about.title': 'About "VereTka" editor',
    'about.p1': '<strong className="text-[var(--text-primary)]">VereTkа</strong> is a simple vector editor designed for quick creation of graphic primitives and generating corresponding Python code for the Tkinter library.',
    'about.p2': 'It uses a local code generator for instant and reliable results, and can also use the Google Gemini API for experimental capabilities.',
    'about.author': '<strong className="text-[var(--text-primary)]">Idea & Development:</strong> Vitaliy Kushnir',
    'about.support': '<strong className="text-[var(--text-primary)]">Support:</strong> AI assistant powered by Google Gemini.',
    'about.tech': 'Created with <a href="https://aistudio.google.com/" target="_blank" rel="noopener noreferrer" className="underline text-[var(--accent-primary)] hover:text-[var(--accent-primary-hover)]">AI Studio Google</a>, Visual Studio Code.',
    'about.version': 'Version',
    'help.intro': '1. Introduction',
    'help.interface': '2. Interface Overview',
    'help.projects': '3. Working with projects',
    'help.templates': '4. Working with templates',
    'help.shapes': '5. Working with shapes',
    'help.codeExport': '6. Code and export',
    'help.feedback': '7. Feedback',
    'help.hotkeys': '8. Hotkeys',
    'saveAs.title': 'Save as...',
    'tool.imageImport': 'Image [import]',
    'canvas.shapeDuplicated': 'Shape duplicated.',
    'canvas.finish': 'Finish',
    'canvas.closePoly': 'Close path',
    'canvas.duplicating': 'Duplicating',
    'canvas.angle': 'Angle',
    'selection.anchorPoint': 'Text anchor point',
`;

let transCode = fs.readFileSync('lib/translations.ts', 'utf8');
transCode = transCode.replace(/'action\.save': 'Зберегти',/g, "'action.save': 'Зберегти',\n" + ukEdits);
transCode = transCode.replace(/'action\.save': 'Save',/g, "'action.save': 'Save',\n" + enEdits);

fs.writeFileSync('lib/translations.ts', transCode);
console.log('done trans 4');
